name: Auto-Assign Poject to Issue
run-name: Issue ${{ github.event.issue.number }} → Project ${{ vars.PROJECT }}
on:
  issues:
    types: [opened, edited, reopened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/Netcracker/projects/${{ vars.PROJECT }}?type=beta
          github-token: ${{ secrets.ADD_PROJECT_TO_ISSUE_PAT }}
