name: JAR deletion
on:
  workflow_dispatch:

jobs:
  delete-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete JAR files
        uses: nookyo/qubership-workflow-hub/actions/container-package-cleanup@main
