name: Test Workflow for JAR Deletion
on:
  workflow_dispatch:

jobs:
  delete-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete JAR files
        uses: nookyo/qubership-workflow-hub/actions/container-package-cleanup@main
        with:
          package-type: 'maven' # Specify the package type to delete
          dry-run: true # Set to true to perform a dry run without actual deletion
        env:
          PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token for authentication
